### ISSUE TITLE
UnsupportedOperation: not writable

### ISSUE THREAD

**Issue by 14H034160212** [allenai/aristo-mini#42]
Hi,

I meet a issue when I run the project. The detail is the following message. Does anyone know hoe to solve the issue? Thank you so much.

```
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 6.4.0 -- An enhanced Interactive Python.

runfile('H:/789/aristo-mini-master/aristo-mini-master/aristomini/solvers/randomguesser.py', wdir='H:/789/aristo-mini-master/aristo-mini-master/aristomini/solvers')
Traceback (most recent call last):
  File "<ipython-input-1-1b29279ad79e>", line 1, in <module>
    runfile('H:/789/aristo-mini-master/aristo-mini-master/aristomini/solvers/randomguesser.py', wdir='H:/789/aristo-mini-master/aristo-mini-master/aristomini/solvers')
  File "C:\Users\qbao775\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)
  File "C:\Users\qbao775\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "H:/789/aristo-mini-master/aristo-mini-master/aristomini/solvers/randomguesser.py", line 27, in <module>
    solver.run()
  File "H:\789\aristo-mini-master\aristo-mini-master\aristomini\common\solver.py", line 41, in run
    app.run(host=host, port=port)
  File "C:\Users\qbao775\AppData\Local\Continuum\anaconda3\lib\site-packages\flask\app.py", line 938, in run
    cli.show_server_banner(self.env, self.debug, self.name, False)
  File "C:\Users\qbao775\AppData\Local\Continuum\anaconda3\lib\site-packages\flask\cli.py", line 629, in show_server_banner
    click.echo(message)
  File "C:\Users\qbao775\AppData\Local\Continuum\anaconda3\lib\site-packages\click\utils.py", line 259, in echo
    file.write(message)
```

**Comment by dirkgr** [comment]
I'm not sure what's going on here, but I suspect the problem is that you're running Windows. I don't think Windows is a supported platform for aristo-mini.

**Comment by aimichal** [comment]
@joelgrus can you take quick a look in case it's something obvious?

**Comment by joelgrus** [comment]
can you share the actual error message? it's hard to know what went wrong without it

**Comment by 14H034160212** [comment]
Sorry for the late feedback. I have solved the problem. I have another general question about the possible methods that we can use. In your project, you have used the random answer selection. Have you try some different methods? Currently I have try two methods, the first method is to compare the similarity of question and each option and then pick the highest similarity one as the predict answer. The second one is I have some history question data, and I have try to select top t similar questions for a question. The result is the sum of the similarity of top t similar question. Those two methods are my current methods. Do you have any idea? Thank you so much.
